export enum NotesErrorType {
  NETWORK_ERROR = "NETWORK_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
  CONFLICT_ERROR = "CONFLICT_ERROR",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",
  OFFLINE_ERROR = "OFFLINE_ERROR",
  SYNC_ERROR = "SYNC_ERROR",
}
