export enum StorageErrorType {
  SERIALIZATION_ERROR = "SERIALIZATION_ERROR",
  QUOTA_EXCEEDED = "QUOTA_EXCEEDED",
  ACCESS_DENIED = "ACCESS_DENIED",
  DATA_CORRUPTION = "DATA_CORRUPTION",
  NETWORK_ERROR = "NETWORK_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
